apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c8di
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-c8di@sha256:183537473c14c6e637969b75fb7f697956d0f178fdea2af8e53cd3d8701ae50a
        name: my-nodejs
        resources: {}
status: {}
